import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Roboto } from 'next/font/google';
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const roboto = Roboto({
  subsets: ['latin'], // Inclui os caracteres padrão
  weight: ['400', '700'], // Escolha os pesos desejados
  variable: '--font-roboto', // Cria uma variável CSS para Tailwind
});

export const metadata: Metadata = {
  title: {
    template: "%s Bruno Ferraz Sabino - Portfólio",
    default: "Bruno Ferraz Sabino - Portfólio"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={` ${roboto.variable} antialiased  md:mx-auto bg-[#FAF5EA] `} // ${geistSans.variable} ${geistMono.variable}
      >
        <Header />
        <main className="container mx-auto">{children}</main>
        <footer className="bg-[#001726] bg-primary text-white">
          <div className="container mx-auto text-center p-8 font-bold font-sans">
            Feito com &#x1F496; por Bruno Ferraz Sabino
          </div>
        </footer>
      </body>
    </html>
  );
}
