import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Separator } from "@/components/ui/separator";
import { NavigationMenuDemo } from "@/components/menu";
import { Roboto } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const roboto = Roboto({
  subsets: ['latin'], // Inclui os caracteres padrão
  weight: ['400', '700'], // Escolha os pesos desejados
  variable: '--font-roboto', // Cria uma variável CSS para Tailwind
});

export const metadata: Metadata = {
  title: {
    template: "%s Bruno Ferraz Sabino - Portfólio",
    default: "Bruno Ferraz Sabino - Portfólio"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={` ${roboto.variable} antialiased container  md:mx-auto`} // ${geistSans.variable} ${geistMono.variable}
      >
        <header className="flex p-4  ">
          <div className="flex-1 ">
            <div className="p-2">
              BRUNO FERRAZ SABINO
            </div>
            <Separator className="" />

          </div>
          <div className=" ">
            <Separator orientation="vertical" />
          </div>
          <div className="">
            <Separator className="" />
            <div className="flex">
              <NavigationMenuDemo />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
